// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-PXL_LDqSUbIdNN7z2VG1A8-SD9EsJ8',
    appId: '1:583809613806:web:9be84330945bd95984d8ff',
    messagingSenderId: '583809613806',
    projectId: 'experiements-6e557',
    authDomain: 'experiements-6e557.firebaseapp.com',
    storageBucket: 'experiements-6e557.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHO7p1fvu0alI32p-9SG_2CG682Zhopsg',
    appId: '1:583809613806:android:251400d7dfd741d184d8ff',
    messagingSenderId: '583809613806',
    projectId: 'experiements-6e557',
    storageBucket: 'experiements-6e557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwdTlib7pIGn4VThbhq0MUFnyzC6ieP8',
    appId: '1:583809613806:ios:4a85db351c5805e484d8ff',
    messagingSenderId: '583809613806',
    projectId: 'experiements-6e557',
    storageBucket: 'experiements-6e557.firebasestorage.app',
    iosBundleId: 'com.example.experiments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwdTlib7pIGn4VThbhq0MUFnyzC6ieP8',
    appId: '1:583809613806:ios:4a85db351c5805e484d8ff',
    messagingSenderId: '583809613806',
    projectId: 'experiements-6e557',
    storageBucket: 'experiements-6e557.firebasestorage.app',
    iosBundleId: 'com.example.experiments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ-PXL_LDqSUbIdNN7z2VG1A8-SD9EsJ8',
    appId: '1:583809613806:web:cbc64911f50adbec84d8ff',
    messagingSenderId: '583809613806',
    projectId: 'experiements-6e557',
    authDomain: 'experiements-6e557.firebaseapp.com',
    storageBucket: 'experiements-6e557.firebasestorage.app',
  );

}